#pragma once

enum
{
	CLASSID_UNKNOWN = 0,
	CLASSID_PARTICLESYSTEM,
	CLASSID_SUPERSPRAY,
	CLASSID_PARRAY,
	CLASSID_DECAL,

	CLASSID_SUPERDECAL,			//	5
	CLASSID_BILLBOARD,
	CLASSID_SNOW,
	CLASSID_RAIN,
	CLASSID_STREAM,

	CLASSID_GRAPHICSFX,			//	10
	CLASSID_GFXPLAYEVENT,
	CLASSID_CONTROLLEDJOINT,
	CLASSID_BONE,
	CLASSID_JOINT,

	CLASSID_ANIMJOINT,			//	15
	CLASSID_SPRINGJOINT,
	CLASSID_AXISSPRINGJOINT,
	CLASSID_COORDINATE,
	CLASSID_SKINMODEL,

	CLASSID_SKINMODELACTIONCORE,//	20
	CLASSID_SKELETONHOOK,
	CLASSID_SKIN,
	CLASSID_SKELETON,
	CLASSID_SKINHITBOX,

	CLASSID_PIXELSHADER,		//	25
	CLASSID_VERTEXSHADER,
	CLASSID_MESHBASE,
	CLASSID_SKINMESH,
	CLASSID_RIGIDMESH,

	CLASSID_MORPHSKINMESH,		//	30
	CLASSID_MORPHRIGIDMESH,
	CLASSID_HANGER,
	CLASSID_GFXHANGER,
	CLASSID_SKINMODELHANGER,

	CLASSID_SUPPLEMESH,			//	35
	CLASSID_SUPPLEMESHIMP,
	CLASSID_SKINPHYSHAPE,
	CLASSID_CAMERABASE,
	CLASSID_CAMERA,

	CLASSID_ORTHOCAMERA,		//	40
	CLASSID_MUSCLEMESH,
	CLASSID_MUSCLEMESHIMP,
	CLASSID_CLOTHMESHIMP,
	CLASSID_HLSL,

	CLASSID_HLSLCORE,			//  45
	CLASSID_HLSLSHADER,
	CLASSID_RENDERTARGET,
	CLASSID_TEXTURE2D,
	CLASSID_TEXTURE3D,

	CLASSID_TEXTURECUBE,		//  50
	CLASSID_SKINRENDER,
	CLASSID_SKINRENDERWITHEFFECT,
	CLASSID_SHADER,
};

